services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    # 起動し続けるための設定
    tty: true

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: edinet_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
